version: "3.9"
services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    working_dir: /srv/docker-server/
    volumes:
      - ./:/srv/docker-server/
    env_file:
      - ./.env
    restart: always
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static/:/static
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always



