version: "3.8"
services:

  redis:
    image: redis:5
    command: redis-server --port 6379
    ports:
      - 6379:6379

  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    working_dir: /srv/docker-server/
    volumes:
      - ./:/srv/docker-server/
    env_file:
      - ./.env
    restart: always
    
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static/:/static
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - asgiserver
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    
  asgiserver:
    build: .
    command: daphne -u /tmp/daphne.sock petrasche.asgi:application --bind 0.0.0.0 -p 8001
    ports:
      - 8001:8001
    working_dir: /srv/docker-server/
    volumes:
      - ./:/srv/docker-server/
    env_file:
      - ./.env
    expose:
      - 8001
